image: php:alpine3.7

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
  #- docker build -t registry.gitlab.com/chamunks/concrete5/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHA .
  - docker build -t registry.gitlab.com/chamunks/concrete5/$CI_COMMIT_REF_NAME:latest .
  #- docker push registry.gitlab.com/chamunks/concrete5/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHA
  #- docker tag registry.gitlab.com/chamunks/concrete5/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHA registry.gitlab.com/chamunks/concrete5/$CI_COMMIT_REF_NAME:latest
  - docker push registry.gitlab.com/chamunks/concrete5/$CI_COMMIT_REF_NAME:latest
  # - sed -i 's/CI_COMMIT_REF_NAME/$CI_COMMIT_REF_NAME/g' ./docker-compose.yml
  - docker pull registry.gitlab.com/chamunks/concrete5/$CI_COMMIT_REF_NAME:latest
