#############################
## MySQL/MariaDB Container ##
#############################
db:
  image: mariadb
  restart: always
  environment:
  - MYSQL_ROOT_PASSWORD=the_db_root_password
  - MYSQL_USER=c5dbadmin
  - MYSQL_PASSWORD=the_db_user_password
  - MYSQL_DATABASE=c5db
  log_opt:
    max-size: "256k"
    max-file: "10"
  # host volume
  volumes:
    - ./data/var/lib/mysql:/var/lib/mysql
    networks:
      green:
        ###################################################################
        ## You can define the IP addresses statically here if you linked
        ## You will have to uncomment the ipam config line below in the
        ## Networks block at the bottom.
        ###################################################################
        # ipv4_address: 10.5.0.5
        aliases:
          - mysql
#########################
## Concrete5 container ##
#########################
web:
  image: chriswayg/concrete5.7
  restart: always
  ports:
  - "80:80"
  - "443:443"
  ##############################################################################
  ## If you put a reverse proxy in front of this you can delete the Ports block
  ## and uncomment the Expose block then use Docker Networking to connect
  ## this container to the reverse proxy.
  ##############################################################################
  # expose:
  #   - 80
  #   - 443
  links:
  - db
  depends_on:
    - db
  log_opt:
    max-size: "512k"
    max-file: "50"
  #############################################################################
  ## host volumes
  ## You can uncomment this section if you want to enable host based Volumes
  #############################################################################
  volumes:
    - ./data/etc/apache2:/etc/apache2
    - ./data/html:/var/www/html
    - ./data/config:/var/www/html/config
    networks:
      green:
        ###################################################################
        ## You can define the IP addresses statically here if you linked
        ## You will have to uncomment the ipam config line below in the
        ## Networks block at the bottom.
        ###################################################################
        # ipv4_address: 10.5.0.6

#########################
## Network Definitions ##
#########################
networks:
  green:
    driver: bridge
    ##################################################################
    ## Uncomment to enable static IP's within the container cluster.
    ##################################################################
    # ipam:
    #     config:
    #       - subnet: 10.5.0.0/16
