#############################
## MySQL/MariaDB Container ##
#############################
db:
  image: mariadb
  restart: always
  #############################################################################
  ## Database configuration
  ## As mentioned in the README.md file you should really change the values
  ## after the equals sign below in the environment directive values.
  #############################################################################
  environment:
  - MYSQL_ROOT_PASSWORD=c5db_database_root_password
  - MYSQL_USER=c5db_user
  - MYSQL_PASSWORD=c5db_database_password
  - MYSQL_DATABASE=c5db_database
  log_opt:
    max-size: "256k"
    max-file: "10"
  #############################################################################
  ## host volume, you may consider using actual docker volumes in the future.
  #############################################################################
  volumes:
    - ./data/var/lib/mysql:/var/lib/mysql
  networks:
    green:
      ###################################################################
      ## You can define the IP addresses statically here if you linked
      ## You will have to uncomment the ipam config line below in the
      ## Networks block at the bottom.
      ###################################################################
      ipv4_address: 10.5.0.5
      aliases:
        - mysql
#########################
## Concrete5 container ##
#########################
web:
  image: chamunks/concrete5
  restart: always
  ports:
  - "80:80"
  links:
  - db
  depends_on:
    - db
  log_opt:
    max-size: "512k"
    max-file: "50"
  #############################################################################
  ## host volumes
  ## You can uncomment this section if you want to enable host based Volumes
  #############################################################################
  volumes:
    - ./data/etc/apache2:/etc/apache2
    - ./data/html:/var/www/html
    - ./data/config:/var/www/html/config
  networks:
    green:
      ###################################################################
      ## You can define the IP addresses statically here if you linked
      ## You will have to uncomment the ipam config line below in the
      ## Networks block at the bottom.
      ###################################################################
      ipv4_address: 10.5.0.6

#########################
## Network Definitions ##
#########################
networks:
  green:
    driver: bridge
    ipam:
        config:
          - subnet: 10.5.0.0/16
